"""Statiske referansedata: kilder, kategorier, mottakere.

Kategorier og kildelister er *definisjoner* (hvordan vi avgrenser), ikke tall.
Beskrivelser og forpliktelses-klassifisering er et utkast som må kvalitetssikres
mot UD/Finansdepartementet før publisering (se docs/datahull.md).
"""

SOURCES = [
    # id, navn, url, utgiver, tilgang
    ("statsbudsjettet", "Statsbudsjettet (Prop. 1 S) og Gul bok", "https://www.statsbudsjettet.no/", "Finansdepartementet", "download"),
    ("rnb", "Revidert nasjonalbudsjett", "https://www.regjeringen.no/no/tema/okonomi-og-budsjett/statsbudsjett/id1412/", "Finansdepartementet", "download"),
    ("statsregnskapet", "Statsregnskapet", "https://www.statsregnskapet.no/", "Direktoratet for forvaltning og økonomistyring (DFØ)", "download"),
    ("stortinget", "Stortingets åpne data (saker og vedtak)", "https://data.stortinget.no/", "Stortinget", "api"),
    ("norad", "Norads bistandsstatistikk / resultatportal", "https://resultater.norad.no/", "Norad", "download"),
    ("oecd_dac", "OECD DAC – bistand per mottaker og sektor", "https://data-explorer.oecd.org/", "OECD", "api"),
    ("ssb", "SSB StatBank (befolkning, BNP, KPI, skattytere)", "https://www.ssb.no/statbank", "Statistisk sentralbyrå", "api"),
    ("ssb_kostra", "SSB KOSTRA (kommunale enhetskostnader)", "https://www.ssb.no/kostra", "Statistisk sentralbyrå", "api"),
    ("ud", "Utenriksdepartementet (bidrag til FN, NATO m.fl.)", "https://www.regjeringen.no/no/dep/ud/id833/", "Utenriksdepartementet", "manual"),
    ("fd", "Forsvarsdepartementet (NATO-bidrag)", "https://www.regjeringen.no/no/dep/fd/id380/", "Forsvarsdepartementet", "manual"),
    ("finansdep_skatt", "Finansdepartementet – skatteprovenyanslag", "https://www.regjeringen.no/no/dep/fin/id216/", "Finansdepartementet", "manual"),
    ("vegvesen", "Statens vegvesen / Nasjonal transportplan", "https://www.vegvesen.no/", "Statens vegvesen", "manual"),
    ("datanorge", "data.norge.no (åpne datasett)", "https://data.norge.no/", "Digitaliseringsdirektoratet", "api"),
]

CATEGORIES = [
    dict(id="dev", name_nb="Utviklingshjelp (bilateral)", name_en="Development aid (bilateral)",
         description_nb="Langsiktig bistand til utviklingsland: utdanning, helse, næringsutvikling, styresett.",
         description_en="Long-term aid to developing countries: education, health, economic development, governance.",
         nature="grant", commitment="political",
         commitment_note_nb="Politisk vedtatt nivå; Norge har et langvarig politisk mål om 1 % av BNI, men det er ikke en folkerettslig forpliktelse.",
         commitment_note_en="Politically decided level; Norway has a long-standing political target of 1% of GNI, not a treaty obligation."),
    dict(id="hum", name_nb="Humanitær bistand", name_en="Humanitarian assistance",
         description_nb="Nødhjelp og beskyttelse ved kriser, krig og naturkatastrofer.",
         description_en="Emergency relief and protection in crises, war and natural disasters.",
         nature="grant", commitment="political",
         commitment_note_nb="Politisk vedtatt; fordeles fortløpende etter behov og kan justeres gjennom året.",
         commitment_note_en="Politically decided; allocated as needs arise and adjustable during the year."),
    dict(id="ukr", name_nb="Ukraina-støtte (Nansen-programmet)", name_en="Ukraine support (Nansen Programme)",
         description_nb="Militær og sivil støtte til Ukraina, inkludert gjenoppbygging og energi.",
         description_en="Military and civilian support for Ukraine, including reconstruction and energy.",
         nature="mixed", commitment="political",
         commitment_note_nb="Flerårig politisk vedtak (Stortinget). Kan omfatte både gaver og lån; fordeling må kvalitetssikres mot primærkilde.",
         commitment_note_en="Multi-year political decision (Storting). May include both grants and loans; split must be verified against primary source."),
    dict(id="org", name_nb="Bidrag til internasjonale organisasjoner", name_en="Contributions to international organisations",
         description_nb="Kjernebidrag og kontingenter til FN-systemet, Verdensbanken, regionale banker og globale fond.",
         description_en="Core contributions and assessed dues to the UN system, World Bank, regional banks and global funds.",
         nature="mixed", commitment="agreement",
         commitment_note_nb="Delvis kontingenter (traktatfestet medlemskap), delvis frivillige kjernebidrag og flerårige avtaler.",
         commitment_note_en="Partly assessed dues (treaty membership), partly voluntary core contributions and multi-year agreements."),
    dict(id="eea", name_nb="EØS-midler / Norway Grants", name_en="EEA and Norway Grants",
         description_nb="Bidrag til sosial og økonomisk utjevning i mottakerland i EØS, samt EU-programdeltakelse.",
         description_en="Contributions to social and economic cohesion in EEA recipient states, plus EU programme participation.",
         nature="grant", commitment="agreement",
         commitment_note_nb="Avtalefestet gjennom EØS-avtalen og femårige forhandlede perioder.",
         commitment_note_en="Agreement-based through the EEA Agreement and negotiated five-year periods."),
    dict(id="def", name_nb="Forsvar / NATO", name_en="Defence / NATO",
         description_nb="Felles finansiering av NATO (sivilt og militært budsjett, NSIP) og relaterte bidrag.",
         description_en="Common funding of NATO (civil and military budgets, NSIP) and related contributions.",
         nature="membership", commitment="treaty",
         commitment_note_nb="Medlemskap i NATO følger av Atlanterhavspakten; felles finansiering fastsettes gjennom NATOs budsjettprosesser.",
         commitment_note_en="NATO membership follows from the North Atlantic Treaty; common funding is set via NATO budget processes."),
    dict(id="clim", name_nb="Klima og skog", name_en="Climate and forests",
         description_nb="Resultatbasert betaling for redusert avskoging og klimatiltak (bl.a. Klima- og skogsatsingen).",
         description_en="Results-based payments for reduced deforestation and climate action (incl. the Climate and Forest Initiative).",
         nature="grant", commitment="agreement",
         commitment_note_nb="Flerårige bilaterale avtaler med resultatbasert utbetaling.",
         commitment_note_en="Multi-year bilateral agreements with results-based disbursement."),
]

# id, nb, en, iso_n3, iso_a3, region
COUNTRIES = [
    ("ukr", "Ukraina", "Ukraine", 804, "UKR", "Europa"),
    ("mda", "Moldova", "Moldova", 498, "MDA", "Europa"),
    ("geo", "Georgia", "Georgia", 268, "GEO", "Europa"),
    ("tza", "Tanzania", "Tanzania", 834, "TZA", "Afrika"),
    ("uga", "Uganda", "Uganda", 800, "UGA", "Afrika"),
    ("moz", "Mosambik", "Mozambique", 508, "MOZ", "Afrika"),
    ("mwi", "Malawi", "Malawi", 454, "MWI", "Afrika"),
    ("zmb", "Zambia", "Zambia", 894, "ZMB", "Afrika"),
    ("eth", "Etiopia", "Ethiopia", 231, "ETH", "Afrika"),
    ("som", "Somalia", "Somalia", 706, "SOM", "Afrika"),
    ("ssd", "Sør-Sudan", "South Sudan", 728, "SSD", "Afrika"),
    ("sdn", "Sudan", "Sudan", 729, "SDN", "Afrika"),
    ("cod", "DR Kongo", "DR Congo", 180, "COD", "Afrika"),
    ("ken", "Kenya", "Kenya", 404, "KEN", "Afrika"),
    ("mli", "Mali", "Mali", 466, "MLI", "Afrika"),
    ("ner", "Niger", "Niger", 562, "NER", "Afrika"),
    ("nga", "Nigeria", "Nigeria", 566, "NGA", "Afrika"),
    ("gha", "Ghana", "Ghana", 288, "GHA", "Afrika"),
    ("lbr", "Liberia", "Liberia", 430, "LBR", "Afrika"),
    ("nep", "Nepal", "Nepal", 524, "NPL", "Asia"),
    ("afg", "Afghanistan", "Afghanistan", 4, "AFG", "Asia"),
    ("syr", "Syria", "Syria", 760, "SYR", "Asia"),
    ("lbn", "Libanon", "Lebanon", 422, "LBN", "Asia"),
    ("jor", "Jordan", "Jordan", 400, "JOR", "Asia"),
    ("pse", "Palestina", "Palestine", 275, "PSE", "Asia"),
    ("yem", "Jemen", "Yemen", 887, "YEM", "Asia"),
    ("irq", "Irak", "Iraq", 368, "IRQ", "Asia"),
    ("bgd", "Bangladesh", "Bangladesh", 50, "BGD", "Asia"),
    ("mmr", "Myanmar", "Myanmar", 104, "MMR", "Asia"),
    ("pak", "Pakistan", "Pakistan", 586, "PAK", "Asia"),
    ("idn", "Indonesia", "Indonesia", 360, "IDN", "Asia"),
    ("ind", "India", "India", 356, "IND", "Asia"),
    ("col", "Colombia", "Colombia", 170, "COL", "Latin-Amerika"),
    ("bra", "Brasil", "Brazil", 76, "BRA", "Latin-Amerika"),
    ("guy", "Guyana", "Guyana", 328, "GUY", "Latin-Amerika"),
    ("per", "Peru", "Peru", 604, "PER", "Latin-Amerika"),
    ("hti", "Haiti", "Haiti", 332, "HTI", "Latin-Amerika"),
    ("pol", "Polen", "Poland", 616, "POL", "Europa"),
    ("rou", "Romania", "Romania", 642, "ROU", "Europa"),
    ("bgr", "Bulgaria", "Bulgaria", 100, "BGR", "Europa"),
    ("ltu", "Litauen", "Lithuania", 440, "LTU", "Europa"),
    ("lva", "Latvia", "Latvia", 428, "LVA", "Europa"),
    ("est", "Estland", "Estonia", 233, "EST", "Europa"),
    ("cze", "Tsjekkia", "Czechia", 203, "CZE", "Europa"),
    ("svk", "Slovakia", "Slovakia", 703, "SVK", "Europa"),
    ("hun", "Ungarn", "Hungary", 348, "HUN", "Europa"),
    ("hrv", "Kroatia", "Croatia", 191, "HRV", "Europa"),
    ("grc", "Hellas", "Greece", 300, "GRC", "Europa"),
    ("prt", "Portugal", "Portugal", 620, "PRT", "Europa"),
]

MULTILATERALS = [
    ("m_un", "multilateral", "FN-systemet", "UN system"),
    ("m_wb", "multilateral", "Verdensbanken-gruppen", "World Bank Group"),
    ("m_eu", "multilateral", "EU-programmer (f.eks. Horisont Europa, Erasmus+)", "EU programmes (e.g. Horizon Europe, Erasmus+)"),
    ("m_nato", "multilateral", "NATO", "NATO"),
    ("m_rdb", "multilateral", "Regionale utviklingsbanker", "Regional development banks"),
    ("m_gf", "multilateral", "Globale fond (Gavi, Det globale fondet m.fl.)", "Global funds (Gavi, Global Fund etc.)"),
    ("m_unalloc", "unallocated", "Ikke fordelt på mottaker (regionalt/globalt)", "Unallocated (regional/global)"),
]
