import type { Lang } from "./types";

const nb: Record<string, string> = {
  "site.name": "Norges utenlandsteller",
  skip: "Hopp til hovedinnhold",
  "nav.aria": "Hovednavigasjon", "nav.home": "Forside", "nav.map": "Kart", "nav.categories": "Kategorier", "nav.whatif": "Hva kunne vi gjort?", "nav.method": "Metode og kilder",
  "theme.dark": "Mørkt tema", "theme.light": "Lyst tema", "lang.switch": "Switch to English",
  "banner.label": "Demo.", "banner.more": "Les mer om dataene.",
  "data.loading": "Laster data …", "data.error": "Kunne ikke laste datasettet",
  unverified: "Eksempeldata", "unverified.title": "Dette tallet er illustrativt og ikke hentet fra en kilde.",
  "footer.updated": "Datasett generert {gen}. Siste vellykkede henting fra kilder: {live}.",
  "footer.never": "aldri (demodata)",
  "footer.disclaimer": "Telleren er en estimert fordeling av budsjettvedtak, ikke faktiske transaksjoner. «Hva kunne vi gjort?» er scenarier, ikke fakta.",
  "footer.download": "Last ned data (CSV/JSON)", "footer.source": "Kildekode",
  "ticker.lead": "Norge har sendt ut dette til utlandet hittil i {year} (estimat)",
  "ticker.sr": "Estimert årsbeløp for året er {annual} kroner, som tilsvarer {perSecond} kroner per sekund.",
  "unit.kr": "kroner", "unit.bn": "mrd. kr",
  "ticker.persec": "kroner per sekund",
  "ticker.disclaimer": "Dette er en estimert, jevn fordeling av årets vedtatte budsjett over året, ikke faktiske sanntidstransaksjoner.",
  "kf.title": "Nøkkeltall", "kf.total": "Totalt hittil i år", "kf.perCapita": "Per innbygger", "kf.perTaxpayer": "Per skattebetaler", "kf.perDay": "Per dag",
  "kf.note": "Innbyggere: {pop}. Skattebetalere: {tax}. Beløp hittil i år etter samme jevne fordeling som telleren.",
  "how.title": "Slik regner vi", "how.estimate": "Dette er et estimat.", "how.estimate2": "Telleren viser ikke utbetalinger i sanntid, men årets budsjett delt jevnt utover året.",
  "how.s1": "Vi summerer årets beløp i utvalgte budsjettposter: {total} (grunnlag: {basis}).",
  "how.s2": "Vi deler på antall sekunder i {year} (Europe/Oslo): {secs}.",
  "how.s3": "Det gir {rate} kroner per sekund, regnet fra 1. januar kl. 00:00.",
  "how.s4": "Telleren i nettleseren regner ut verdien fra klokken din hver skjermoppdatering, så alle ser samme tall.",
  "how.formula": "hittil = årsbeløp × (nå − 1. jan 00:00) / (sekunder i året)",
  "how.limits": "Faktiske utbetalinger skjer ujevnt, og årets tall revideres (revidert nasjonalbudsjett, regnskap).", "how.more": "Se metode og kilder.",
  "hist.title": "Utvikling siste 10 år", "hist.price": "Prisgrunnlag", "hist.nominal": "Løpende kroner", "hist.real": "Faste {year}-kroner",
  "hist.aria": "Søylediagram over årlig beløp de siste ti årene. Tabell finnes under diagrammet.",
  "hist.legend": "Mørke søyler: regnskap. Lyse søyler: vedtatt budsjett (ikke endelig).", "hist.table": "Vis som tabell",
  "col.year": "År", "col.amount": "Beløp", "col.basis": "Grunnlag", "col.country": "Land", "col.region": "Region", "col.source": "Kilde", "col.publisher": "Utgiver", "col.access": "Tilgang", "col.status": "Status", "col.retrieved": "Sist hentet",
  "basis.vedtatt": "Vedtatt budsjett", "basis.regnskap": "Regnskap", "basis.estimat": "Estimat",
  "home.scope": "Hva er med?", "home.scope2": "Vi teller utgifter over statsbudsjettet som går til mottakere utenfor Norge, avgrenset til kategoriene under. Avgrensningen er forklart under Metode og kilder.",
  "home.map": "Se hvem som mottar, på kart og i liste.", "home.categories": "Fordeling på formål, med gave/lån og forpliktelser.", "home.whatif": "Sammenlign beløp med norske tiltak. Scenarier.", "home.method": "Datakilder, avgrensning og kjente hull.",
  "map.intro": "Land er farget etter beløp for valgt år. Pilene viser de største mottakerne. Klikk på et land (eller en rad) for detaljer. Internasjonale organisasjoner vises i egen liste.",
  "map.aria": "Verdenskart fargelagt etter beløp per mottakerland. Samme data finnes i tabellen under kartet.",
  "map.legend": "Mill. kr:", "map.nodata": "Ingen data / utenfor filter", "map.arcs": "Piler: de {n} største mottakerlandene, tykkelse etter beløp.",
  "map.summary": "{year}: {total} fordelt på {n} mottakere etter gjeldende filter.",
  "filter.aria": "Filtre", "filter.year": "År", "filter.search": "Søk etter land eller mottaker", "filter.search.ph": "f.eks. Tanzania", "filter.min": "Minst (mill. kr)", "filter.max": "Høyst (mill. kr)", "filter.cats": "Kategorier", "filter.all": "Alle",
  "list.countries": "Mottakerland", "list.others": "Internasjonale organisasjoner og øvrige", "list.others.note": "Mottakere som ikke er land: FN, Verdensbanken, EU-programmer, NATO m.fl. samt beløp som ikke er fordelt på mottaker.", "list.empty": "Ingen treff.",
  "panel.hint": "Velg et land i kartet eller tabellen for å se fordeling, tidslinje, prosjekter og kilder.",
  "panel.close": "Lukk panel", "panel.total": "Totalt {year}", "panel.bycat": "Fordeling per kategori", "panel.none": "Ingen beløp registrert for {year}.",
  "panel.timeline": "Tidslinje per år", "panel.timeline.aria": "Stablet søylediagram over beløp per år og kategori for {name}.", "panel.unit.mnok": "Mill. kr, løpende kroner.",
  "panel.projects": "Største enkeltprosjekter/tilskudd ({year})", "panel.grantee": "Mottaker", "panel.noprojects": "Ingen prosjektdata tilgjengelig for denne mottakeren.",
  "kind.multilateral": "Internasjonal organisasjon / program", "kind.unallocated": "Ikke fordelt på mottaker", "kind.country": "Land",
  "src.retrieved": "hentet {date}", "src.notretrieved": "ikke hentet (eksempeldata)",
  "nature.grant": "Gave/tilskudd", "nature.loan": "Lån", "nature.mixed": "Gaver og lån", "nature.membership": "Medlemskap/kontingent",
  "commitment.treaty": "Traktatfestet", "commitment.agreement": "Avtalefestet", "commitment.political": "Politisk vedtatt",
  "cat.intro": "Hvordan beløpet fordeler seg på formål. Klassifisering av gave/lån og forpliktelsesgrad er et utkast som skal kvalitetssikres mot primærkilder.",
  "cat.stack": "Utvikling per kategori", "cat.stack.aria": "Stablet søylediagram over årlig beløp per kategori.", "cat.unit": "Mrd. kr.", "cat.details": "Kategorier",
  "cat.nature": "Type", "cat.commitment": "Forpliktelse", "cat.top": "Største mottakere",
  "calc.scenario": "Scenario, ikke fakta",
  "calc.intro": "Velg en sum eller en utgiftspost og se hva den tilsvarer i norske termer. Enhetspriser og provenyanslag er oppgitt med kilde og usikkerhetsintervall. Dette er regneeksempler, ikke anbefalinger eller prognoser.",
  "calc.step1": "1. Velg beløp", "calc.source": "Beløp fra", "calc.custom": "Egen sum", "calc.p.total": "Hele årets sum", "calc.amount": "Beløp",
  "calc.realnote": "Merk: Beløp for {y} er i løpende {y}-kroner. Enhetspriser er i nyere priser. Gang med {f} for omtrentlig verdi i dagens kroner (se Metode).",
  "calc.step2": "2. Hva tilsvarer beløpet?", "calc.eq.note": "Driftsposter (sykehjemsplass, årsverk, barnehage) gjelder ett år. Investeringer (vei) er engangskostnader. Intervall bruker lav/høy enhetspris.",
  "calc.range": "Intervall", "calc.prices": "{year}-priser",
  "calc.perCapita": "kroner per innbygger", "calc.perCapita.note": "Beløp delt på folketall i {year}. Engangsbeløp, ikke årlig.",
  "calc.tax.title": "Skattekutt: hva man mister", "calc.tax.intro": "Skatter er en inntekt for staten. Å fjerne en skatt gir et proveny-tap som må dekkes av andre inntekter eller kutt. Her vises provenyet som mistes sammen med beløpet du sammenligner med.",
  "calc.tax.pick": "Skattetiltak", "calc.tax.lost": "Proveny staten mister", "calc.tax.cuts": "Beløp (kutt/omprioritering)", "calc.tax.coverage": "Beløpet dekker",
  "calc.tax.bar": "Beløpet dekker {p} av provenytapet.", "calc.tax.gap": "Beløpet dekker ikke hele provenytapet. Gjenstår: {gap} per år.", "calc.tax.surplus": "Beløpet overstiger provenytapet med {s}.",
  "calc.ctx.title": "Kontekst og forbehold", "calc.ctx.committed": "Andel av valgt beløp i kategorier klassifisert som traktat- eller avtalefestet (foreløpig klassifisering): {p}. Dette kan ikke uten videre kuttes.",
  "calc.ctx.c1": "Å «kutte» en budsjettpost gir ikke automatisk et beløp til andre formål. Det avhenger av politiske valg og av hvilke avtaler som kan sies opp.",
  "calc.ctx.c2": "Regnestykkene ser bort fra tilpasningseffekter (atferd, priser, etterspørsel) og fra at noen bistandsutgifter gir økonomisk, sikkerhetspolitisk eller annen nytte for Norge.",
  "calc.ctx.c3": "Bruttobeløp og enhetspriser er statiske anslag for ett prisår.", "calc.ctx.recipient": "Beløpet gjelder mottaker {name} og kan omfatte forpliktelser i flerårige avtaler.",
  "method.intro": "Hvordan tallene er valgt, avgrenset, kategorisert og regnet om. Alt som er eksempeldata er merket.",
  "method.scope.h": "Hva teller vi?", "method.scope.p": "Vi teller utgifter over statsbudsjettet der mottaker er utenfor Norge: bilateral utviklingshjelp, humanitær bistand, Ukraina-støtte, bidrag til internasjonale organisasjoner, EØS-midler/Norway Grants, NATO-bidrag og klima- og skogfinansiering.\nAvgrensningen er en redaksjonell vurdering og er ikke identisk med OECDs ODA-definisjon. Hver kategori er definert på siden Kategorier.",
  "method.counter.h": "Telleren", "method.counter.p": "Telleren tar årets samlede beløp (vedtatt budsjett: saldert budsjett, oppdatert med revidert nasjonalbudsjett) og fordeler det jevnt over alle sekundene i året fra 1. januar kl. 00:00 norsk tid.\nDet er en modell, ikke et regnskap. Faktiske utbetalinger skjer ujevnt. Telleren regnes i nettleseren fra klokken din.",
  "method.basis.h": "Vedtatt, regnskap og estimat", "method.basis.p": "Vedtatt budsjett: beløp Stortinget har vedtatt for året. Regnskap: faktisk bokført etter årets slutt (statsregnskapet / bistandsstatistikk). Estimat: modellert verdi der de to ikke finnes. Hver rad viser sitt grunnlag.",
  "method.prices.h": "Løpende og faste kroner", "method.prices.p": "Alle beløp lagres i løpende kroner (verdien i det året). Faste kroner regnes om med SSBs konsumprisindeks (KPI) til siste år. Diagrammene lar deg bytte.",
  "method.classify.h": "Kategorisering", "method.classify.p": "Kategori følger budsjettkapittel/post og bistandsstatistikk. Noen utgifter kan passe i flere kategorier (for eksempel humanitær støtte til Ukraina); vi plasserer dem der primærkilden gjør det og oppgir dette.",
  "method.contrib.h": "Gaver, lån og forpliktelser", "method.contrib.p": "Vi skiller mellom gaver/tilskudd, lån og medlemskap/kontingent, og mellom traktatfestede, avtalefestede og politisk vedtatte beløp. Klassifiseringen er foreløpig og oppgis per kategori, med forbehold.",
  "method.excluded.h": "Hva er ikke med", "method.excluded.p": "Utgifter til flyktninger i Norge (som kan regnes som bistand i OECDs statistikk), Oljefondets investeringer, garantier som ikke er utbetalt, private gaver og frivillige organisasjoners egne midler.",
  "method.whatif.h": "«Hva kunne vi gjort?»", "method.whatif.p": "Modulen er scenariobasert og merket som det. Enhetspriser hentes fra offisielle kilder og vises med intervall. Skatter er inntekter: vi viser alltid provenyet man mister. Modulen vurderer ikke om tiltak er ønskelige.",
  "method.gaps.h": "Kjente hull", "method.gaps.p": "Automatisk henting er foreløpig skissert for SSB (ikke testet mot live-API). Stortinget er testet og gir kun saksreferanser.\nBeløp per mottaker fra Norad, OECD DAC, statsregnskapet og departementene må importeres fra nedlastede filer (se dokumentasjonen).\nEnhetspriser og proveny er plassholdere til de er verifisert.\nKartet bruker en forenklet verdensgeometri uten små øystater.",
  "method.sources.h": "Datakilder", "method.sources.p": "Status per kilde ved siste kjøring ({date}). «Eksempeldata» betyr at tall fra denne kilden ennå ikke er hentet.",
  "method.dl.h": "Last ned data", "method.dl.p": "Alle datasett som brukes på siden er åpne. Beløp i millioner kroner (løpende), med kilde per rad.",
  "access.api": "API", "access.download": "Nedlasting", "access.scrape": "Skraping", "access.manual": "Manuell",
  "status.live": "Hentet", "status.failed": "Feilet", "status.manual_needed": "Krever manuell import", "status.mock": "Eksempeldata",
};

const en: Record<string, string> = {
  "site.name": "Norway's foreign outlay counter",
  skip: "Skip to main content",
  "nav.aria": "Main navigation", "nav.home": "Home", "nav.map": "Map", "nav.categories": "Categories", "nav.whatif": "What could we do?", "nav.method": "Method and sources",
  "theme.dark": "Dark theme", "theme.light": "Light theme", "lang.switch": "Bytt til norsk",
  "banner.label": "Demo.", "banner.more": "Read more about the data.",
  "data.loading": "Loading data …", "data.error": "Could not load the dataset",
  unverified: "Sample data", "unverified.title": "This figure is illustrative and not retrieved from a source.",
  "footer.updated": "Dataset generated {gen}. Last successful retrieval from sources: {live}.",
  "footer.never": "never (demo data)",
  "footer.disclaimer": "The counter is an estimated distribution of budget decisions, not actual transactions. “What could we do?” shows scenarios, not facts.",
  "footer.download": "Download data (CSV/JSON)", "footer.source": "Source code",
  "ticker.lead": "Norway has sent this abroad so far in {year} (estimate)",
  "ticker.sr": "The estimated annual amount is {annual} kroner, equal to {perSecond} kroner per second.",
  "unit.kr": "kroner", "unit.bn": "bn NOK",
  "ticker.persec": "kroner per second",
  "ticker.disclaimer": "This is an estimated, even distribution of the year's adopted budget across the year, not real-time transactions.",
  "kf.title": "Key figures", "kf.total": "Total so far this year", "kf.perCapita": "Per resident", "kf.perTaxpayer": "Per taxpayer", "kf.perDay": "Per day",
  "kf.note": "Residents: {pop}. Taxpayers: {tax}. Year-to-date amounts use the same even distribution as the counter.",
  "how.title": "How we calculate", "how.estimate": "This is an estimate.", "how.estimate2": "The counter does not show payments in real time; it shows the year's budget spread evenly over the year.",
  "how.s1": "We sum the year's amounts across selected budget lines: {total} (basis: {basis}).",
  "how.s2": "We divide by the number of seconds in {year} (Europe/Oslo): {secs}.",
  "how.s3": "That gives {rate} kroner per second, counted from 1 January 00:00.",
  "how.s4": "The counter in your browser computes the value from your clock on every screen refresh, so everyone sees the same number.",
  "how.formula": "so_far = annual × (now − 1 Jan 00:00) / (seconds in year)",
  "how.limits": "Actual payments are uneven, and the year's figures are revised (revised national budget, accounts).", "how.more": "See method and sources.",
  "hist.title": "Development over the last 10 years", "hist.price": "Price basis", "hist.nominal": "Current NOK", "hist.real": "Constant {year} NOK",
  "hist.aria": "Bar chart of annual amounts over the last ten years. A table is available below the chart.",
  "hist.legend": "Dark bars: accounts. Light bars: adopted budget (not final).", "hist.table": "Show as table",
  "col.year": "Year", "col.amount": "Amount", "col.basis": "Basis", "col.country": "Country", "col.region": "Region", "col.source": "Source", "col.publisher": "Publisher", "col.access": "Access", "col.status": "Status", "col.retrieved": "Last retrieved",
  "basis.vedtatt": "Adopted budget", "basis.regnskap": "Accounts", "basis.estimat": "Estimate",
  "home.scope": "What is included?", "home.scope2": "We count central-government budget outlays whose recipient is outside Norway, limited to the categories below. The delimitation is explained under Method and sources.",
  "home.map": "See who receives, on a map and in a list.", "home.categories": "Split by purpose, grants/loans and commitments.", "home.whatif": "Compare amounts with Norwegian measures. Scenarios.", "home.method": "Data sources, delimitation and known gaps.",
  "map.intro": "Countries are coloured by amount for the selected year. Arrows show the largest recipients. Click a country (or a row) for details. International organisations are listed separately.",
  "map.aria": "World map coloured by amount per recipient country. The same data is in the table below the map.",
  "map.legend": "NOK million:", "map.nodata": "No data / outside filter", "map.arcs": "Arrows: the {n} largest recipient countries, thickness by amount.",
  "map.summary": "{year}: {total} across {n} recipients under current filters.",
  "filter.aria": "Filters", "filter.year": "Year", "filter.search": "Search country or recipient", "filter.search.ph": "e.g. Tanzania", "filter.min": "At least (NOK million)", "filter.max": "At most (NOK million)", "filter.cats": "Categories", "filter.all": "All",
  "list.countries": "Recipient countries", "list.others": "International organisations and other", "list.others.note": "Recipients that are not countries: UN, World Bank, EU programmes, NATO etc., plus amounts not allocated to a recipient.", "list.empty": "No matches.",
  "panel.hint": "Select a country on the map or in the table to see the breakdown, timeline, projects and sources.",
  "panel.close": "Close panel", "panel.total": "Total {year}", "panel.bycat": "Breakdown by category", "panel.none": "No amounts recorded for {year}.",
  "panel.timeline": "Timeline by year", "panel.timeline.aria": "Stacked bar chart of amounts per year and category for {name}.", "panel.unit.mnok": "NOK million, current prices.",
  "panel.projects": "Largest projects/grants ({year})", "panel.grantee": "Grantee", "panel.noprojects": "No project data available for this recipient.",
  "kind.multilateral": "International organisation / programme", "kind.unallocated": "Not allocated to a recipient", "kind.country": "Country",
  "src.retrieved": "retrieved {date}", "src.notretrieved": "not retrieved (sample data)",
  "nature.grant": "Grant", "nature.loan": "Loan", "nature.mixed": "Grants and loans", "nature.membership": "Membership/dues",
  "commitment.treaty": "Treaty-based", "commitment.agreement": "Agreement-based", "commitment.political": "Politically decided",
  "cat.intro": "How the amount splits by purpose. The grant/loan and commitment classification is a draft to be verified against primary sources.",
  "cat.stack": "Development by category", "cat.stack.aria": "Stacked bar chart of annual amounts per category.", "cat.unit": "NOK billion.", "cat.details": "Categories",
  "cat.nature": "Type", "cat.commitment": "Commitment", "cat.top": "Largest recipients",
  "calc.scenario": "Scenario, not fact",
  "calc.intro": "Pick an amount or a budget item and see what it equals in Norwegian terms. Unit costs and revenue estimates are given with sources and uncertainty ranges. These are worked examples, not recommendations or forecasts.",
  "calc.step1": "1. Choose an amount", "calc.source": "Amount from", "calc.custom": "Custom amount", "calc.p.total": "Whole year's total", "calc.amount": "Amount",
  "calc.realnote": "Note: Amounts for {y} are in current {y} kroner. Unit costs are in more recent prices. Multiply by {f} for an approximate value in today's kroner (see Method).",
  "calc.step2": "2. What does the amount equal?", "calc.eq.note": "Running costs (nursing-home place, FTEs, kindergarten) are for one year. Investments (roads) are one-off costs. Ranges use low/high unit cost.",
  "calc.range": "Range", "calc.prices": "{year} prices",
  "calc.perCapita": "kroner per resident", "calc.perCapita.note": "Amount divided by the {year} population. One-off amount, not annual.",
  "calc.tax.title": "Tax cuts: what is lost", "calc.tax.intro": "Taxes are revenue for the state. Removing a tax loses revenue that must be covered by other income or cuts. Shown here is the revenue lost alongside the amount you are comparing with.",
  "calc.tax.pick": "Tax measure", "calc.tax.lost": "Revenue the state loses", "calc.tax.cuts": "Amount (cut/reprioritisation)", "calc.tax.coverage": "The amount covers",
  "calc.tax.bar": "The amount covers {p} of the revenue loss.", "calc.tax.gap": "The amount does not cover the full revenue loss. Remaining: {gap} per year.", "calc.tax.surplus": "The amount exceeds the revenue loss by {s}.",
  "calc.ctx.title": "Context and caveats", "calc.ctx.committed": "Share of the chosen amount in categories classified as treaty- or agreement-based (preliminary classification): {p}. This cannot simply be cut.",
  "calc.ctx.c1": "“Cutting” a budget item does not automatically free money for other purposes. That depends on political choices and on which agreements can be terminated.",
  "calc.ctx.c2": "The calculations ignore adjustment effects (behaviour, prices, demand) and the fact that some aid outlays yield economic, security or other benefits for Norway.",
  "calc.ctx.c3": "Gross amounts and unit costs are static estimates for one price year.", "calc.ctx.recipient": "The amount concerns recipient {name} and may include commitments under multi-year agreements.",
  "method.intro": "How figures were selected, delimited, categorised and converted. Anything that is sample data is flagged.",
  "method.scope.h": "What do we count?", "method.scope.p": "We count central-government budget outlays whose recipient is outside Norway: bilateral development aid, humanitarian assistance, Ukraine support, contributions to international organisations, EEA/Norway Grants, NATO contributions and climate and forest finance.\nThe delimitation is an editorial judgement and is not identical to the OECD ODA definition. Each category is defined on the Categories page.",
  "method.counter.h": "The counter", "method.counter.p": "The counter takes the year's total (adopted budget: the approved budget updated with the revised national budget) and spreads it evenly over every second of the year from 1 January 00:00 Norwegian time.\nIt is a model, not an account. Actual payments are uneven. The counter is computed in the browser from your clock.",
  "method.basis.h": "Adopted, accounts and estimate", "method.basis.p": "Adopted budget: the amount the Storting approved for the year. Accounts: actually booked after year-end (state accounts / aid statistics). Estimate: modelled value where neither exists. Each row states its basis.",
  "method.prices.h": "Current and constant kroner", "method.prices.p": "All amounts are stored in current kroner (the value in that year). Constant kroner are converted with Statistics Norway's consumer price index (CPI) to the latest year. Charts let you switch.",
  "method.classify.h": "Categorisation", "method.classify.p": "Category follows budget chapter/item and aid statistics. Some outlays could fit several categories (e.g. humanitarian support to Ukraine); we place them where the primary source does and state so.",
  "method.contrib.h": "Grants, loans and commitments", "method.contrib.p": "We distinguish grants, loans and membership/dues, and treaty-based, agreement-based and politically decided amounts. The classification is preliminary and given per category, with caveats.",
  "method.excluded.h": "What is not included", "method.excluded.p": "Costs for refugees in Norway (which can count as aid in OECD statistics), Government Pension Fund Global investments, guarantees not paid out, private donations and NGOs' own funds.",
  "method.whatif.h": "“What could we do?”", "method.whatif.p": "The module is scenario-based and labelled as such. Unit costs come from official sources and are shown with ranges. Taxes are revenue: we always show the revenue lost. The module does not judge whether measures are desirable.",
  "method.gaps.h": "Known gaps", "method.gaps.p": "Automatic retrieval is so far only sketched for Statistics Norway and the Storting, and is untested against the live APIs.\nAmounts per recipient from Norad, OECD DAC, the state accounts and ministries must be imported from downloaded files (see the documentation).\nUnit costs and revenue figures are placeholders until verified.\nThe map uses simplified world geometry without small island states.",
  "method.sources.h": "Data sources", "method.sources.p": "Status per source at the last run ({date}). “Sample data” means figures from this source have not yet been retrieved.",
  "method.dl.h": "Download data", "method.dl.p": "All datasets used on this site are open. Amounts in NOK million (current), with a source per row.",
  "access.api": "API", "access.download": "Download", "access.scrape": "Scraping", "access.manual": "Manual",
  "status.live": "Retrieved", "status.failed": "Failed", "status.manual_needed": "Needs manual import", "status.mock": "Sample data",
};

export const DICT: Record<Lang, Record<string, string>> = { nb, en };
