export const stNb: Record<string, string> = {
  "nav.storting": "Stortinget",
  "nav.projects": "Kostnadsutvikling",
  "pr.intro": "Kostnadsutvikling i store statlige prosjekter: opprinnelig kostnadsramme, senere endringer og begrunnelser slik kildene beskriver dem. Kun tall som er godkjent manuelt mot kilden er publisert. Løpende kroner vises ved siden av faste kroner, slik at prisstigning ikke blandes sammen med overskridelse.",
  "pr.updated": "Uttrekk kjørt {date}.", "pr.agency": "Ansvarlig etat", "pr.ministry": "Departement", "pr.status": "Prosjektstatus",
  "pr.none": "Ingen godkjente tall er publisert ennå. {n} kandidattall fra {docs} dokumenter venter på manuell gjennomgang og vises ikke.",
  "pr.change": "Kostnadsramme endret fra {a} ({y0}) til {b} ({y1}): {nom} i løpende kroner.", "pr.change.real": "I faste {base}-kroner: {real}.", "pr.real.na": "Endring i faste kroner er ikke tilgjengelig (prisnivå ukjent).",
  "pr.chart.aria": "Linjediagram over kostnadsramme over tid, løpende og faste kroner. Tabell finnes under.",
  "pr.nominal": "Løpende kroner", "pr.real": "Faste {base}-kroner", "pr.date": "Dato", "pr.type": "Type", "pr.reason": "Begrunnelse i kilden", "pr.src": "Kilde",
  "pr.pl": "prisnivå {y}", "pr.page": "side {n}",
  "pr.kind.cost_frame": "Kostnadsramme", "pr.kind.cost_change": "Endring i ramme", "pr.kind.incurred": "Påløpte kostnader", "pr.kind.status": "Status", "pr.kind.decision": "Vedtak",
  "pr.cause.scope": "Kategori: endret omfang", "pr.cause.price": "Kategori: prisstigning", "pr.cause.requirements": "Kategori: endrede krav", "pr.cause.uncertainty": "Kategori: usikkerhet", "pr.cause.other": "Kategori: annet",
  "pr.queue": "Gjennomgangskø: {n} kandidattall fra {docs} dokumenter (uttrekk {date}). Kandidater er automatisk uttrukket og ikke publisert før de er godkjent.",
  "pr.votes": "Se relaterte voteringer i Stortinget", "pr.docs": "Dokumenter gjennomsøkt ({n})", "pr.blocked": "Proposisjoner på regjeringen.no er ikke tilgjengelige for pipelinen (blokkert) og er ikke gjennomsøkt.",
  "st.title": "Stortinget: saker og voteringer",
  "st.intro": "Voteringer i Stortinget om budsjettsaker og saker knyttet til utgiftsområdene på siden. Oversikten viser hvordan partier og representanter stemte, og hva saken gjaldt. Den sier ikke noe om hvem som er ansvarlig for et utfall utover selve stemmegivningen.",
  "st.details.show": "Vis detaljer", "st.details.hide": "Skjul detaljer",
  "st.updated": "Hentet {date} fra {source}. Lisens: {license}.",
  "st.source": "Originalkilde",
  "st.n": "{n} voteringer i utvalget (av {total}).",
  "st.filters": "Søk og filter", "st.f.q": "Søk i sak, saksnummer eller forslag", "st.f.party": "Parti", "st.f.committee": "Komité", "st.f.area": "Utgiftsområde",
  "st.f.from": "Fra dato", "st.f.to": "Til dato", "st.f.result": "Utfall", "st.f.any": "Alle", "st.f.adopted": "Vedtatt", "st.f.rejected": "Ikke vedtatt",
  "st.f.recorded": "Bare voteringer med registrerte stemmer", "st.f.reset": "Nullstill",
  "st.empty": "Ingen voteringer i utvalget.", "st.more": "Vis flere", "st.loading": "Laster voteringer …",
  "st.case": "Sak", "st.ref": "Saksnummer", "st.date": "Dato", "st.theme": "Votering over", "st.result": "Utfall",
  "st.gjaldt": "Hva saken gjaldt",
  "st.kind.statsbudsjett": "Statsbudsjettet: budsjettvedtak", "st.kind.revidert": "Revidert nasjonalbudsjett", "st.kind.tillegg": "Tilleggsbevilgninger og omprioriteringer",
  "st.kind.endring": "Endring i statsbudsjettet (enkeltstående bevilgning)", "st.kind.annen": "Annen sak knyttet til et utgiftsområde",
  "st.adopted": "Vedtatt", "st.rejected": "Ikke vedtatt",
  "st.for": "For", "st.against": "Mot", "st.absent": "Ikke til stede", "st.total": "Totalt",
  "st.parties.h": "Fordeling per parti", "st.parties.note": "Antall representanter som stemte for, mot eller ikke var til stede. Partiene står i alfabetisk rekkefølge. Andel er av partiets registrerte representanter i voteringen.",
  "st.party": "Parti", "st.share": "Andel for / mot / ikke til stede",
  "st.reps.h": "Representanter", "st.reps.show": "Vis representanter", "st.reps.hide": "Skjul representanter", "st.reps.search": "Søk etter representant", "st.reps.note": "Stemme per representant slik den er registrert av Stortinget. Vararepresentanter står med sitt eget parti.",
  "st.rep": "Representant", "st.county": "Fylke", "st.vote": "Stemme",
  "st.unrecorded": "Ingen stemmer per representant er registrert for denne voteringen ({result}). Parti- og representantfordeling er derfor ikke tilgjengelig.",
  "st.proposals.h": "Forslag det ble stemt over", "st.proposal.by": "Fremsatt av", "st.proposal.none": "Ingen forslagstekst registrert.",
  "st.areas": "Utgiftsområder",
  "st.link": "Se saken på stortinget.no", "st.neutral": "Voteringen viser stemmegivning og ikke hvem som er ansvarlig for et utfall. «Ikke til stede» kan ha ulike årsaker, blant annet permisjon og sykdom.",
  "st.load.err": "Kunne ikke laste stemmer per representant",
  "st.method.h": "Stortinget: saker og voteringer", "st.method.p": "Saker, voteringer og stemmer per representant hentes automatisk fra data.stortinget.no (åpne data, NLOD). Vi tar med budsjettsaker (Prop. 1 S og endringer, revidert nasjonalbudsjett, tilleggsbevilgninger) i de to siste sesjonene, og saker der tittel, emne eller forslagstekst nevner et av områdene bistand, Ukraina/Nansen, FN og internasjonale organisasjoner/EØS, Follobanen eller Regjeringskvartalet (sesjonene 2013–2014 og senere for områdene). Områdekoblingen er en tekstsøk på nøkkelord (pipeline/config/storting.json) og kan gi både treff og mangler. Voteringer uten registrerte stemmer (f.eks. enstemmig vedtatt) har ingen parti- eller representantfordeling.",
};
export const stEn: Record<string, string> = {
  "nav.storting": "Parliament",
  "nav.projects": "Cost development",
  "pr.intro": "Cost development in large state projects: original cost frame, later changes and reasons as the sources describe them. Only figures approved manually against the source are published. Current kroner are shown next to constant kroner so that price growth is not mixed with overrun.",
  "pr.updated": "Extraction run {date}.", "pr.agency": "Responsible agency", "pr.ministry": "Ministry", "pr.status": "Project status",
  "pr.none": "No approved figures are published yet. {n} candidate figures from {docs} documents await manual review and are not shown.",
  "pr.change": "Cost frame changed from {a} ({y0}) to {b} ({y1}): {nom} in current kroner.", "pr.change.real": "In constant {base} kroner: {real}.", "pr.real.na": "Change in constant kroner is not available (price level unknown).",
  "pr.chart.aria": "Line chart of the cost frame over time, current and constant kroner. A table is below.",
  "pr.nominal": "Current kroner", "pr.real": "Constant {base} kroner", "pr.date": "Date", "pr.type": "Type", "pr.reason": "Reason given in the source", "pr.src": "Source",
  "pr.pl": "price level {y}", "pr.page": "page {n}",
  "pr.kind.cost_frame": "Cost frame", "pr.kind.cost_change": "Change in frame", "pr.kind.incurred": "Costs incurred", "pr.kind.status": "Status", "pr.kind.decision": "Decision",
  "pr.cause.scope": "Category: changed scope", "pr.cause.price": "Category: price growth", "pr.cause.requirements": "Category: changed requirements", "pr.cause.uncertainty": "Category: uncertainty", "pr.cause.other": "Category: other",
  "pr.queue": "Review queue: {n} candidate figures from {docs} documents (extraction {date}). Candidates are extracted automatically and not published until approved.",
  "pr.votes": "See related votes in the Storting", "pr.docs": "Documents searched ({n})", "pr.blocked": "Propositions on regjeringen.no are not available to the pipeline (blocked) and were not searched.",
  "st.title": "Parliament: cases and votes",
  "st.intro": "Votes in the Storting on budget cases and cases linked to the spending areas on this site. The overview shows how parties and representatives voted and what the case concerned. It says nothing about responsibility for an outcome beyond the vote itself.",
  "st.details.show": "Show details", "st.details.hide": "Hide details",
  "st.updated": "Retrieved {date} from {source}. Licence: {license}.",
  "st.source": "Original source",
  "st.n": "{n} votes in the selection (of {total}).",
  "st.filters": "Search and filter", "st.f.q": "Search case, case number or proposal", "st.f.party": "Party", "st.f.committee": "Committee", "st.f.area": "Spending area",
  "st.f.from": "From date", "st.f.to": "To date", "st.f.result": "Outcome", "st.f.any": "All", "st.f.adopted": "Adopted", "st.f.rejected": "Not adopted",
  "st.f.recorded": "Only votes with recorded individual votes", "st.f.reset": "Reset",
  "st.empty": "No votes in the selection.", "st.more": "Show more", "st.loading": "Loading votes …",
  "st.case": "Case", "st.ref": "Case number", "st.date": "Date", "st.theme": "Vote on", "st.result": "Outcome",
  "st.gjaldt": "What the case concerned",
  "st.kind.statsbudsjett": "State budget: budget decision", "st.kind.revidert": "Revised national budget", "st.kind.tillegg": "Supplementary appropriations and reprioritisations",
  "st.kind.endring": "Amendment to the state budget (single appropriation)", "st.kind.annen": "Other case linked to a spending area",
  "st.adopted": "Adopted", "st.rejected": "Not adopted",
  "st.for": "For", "st.against": "Against", "st.absent": "Not present", "st.total": "Total",
  "st.parties.h": "Breakdown by party", "st.parties.note": "Number of representatives who voted for, against or were not present. Parties are listed alphabetically. Share is of the party's registered representatives in the vote.",
  "st.party": "Party", "st.share": "Share for / against / not present",
  "st.reps.h": "Representatives", "st.reps.show": "Show representatives", "st.reps.hide": "Hide representatives", "st.reps.search": "Search for a representative", "st.reps.note": "Vote per representative as recorded by the Storting. Deputy representatives are listed with their own party.",
  "st.rep": "Representative", "st.county": "County", "st.vote": "Vote",
  "st.unrecorded": "No individual votes are recorded for this vote ({result}), so no party or representative breakdown is available.",
  "st.proposals.h": "Proposals voted on", "st.proposal.by": "Put forward by", "st.proposal.none": "No proposal text recorded.",
  "st.areas": "Spending areas",
  "st.link": "See the case on stortinget.no", "st.neutral": "A vote shows how members voted, not who is responsible for an outcome. “Not present” can have several causes, including leave and illness.",
  "st.load.err": "Could not load individual votes",
  "st.method.h": "Parliament: cases and votes", "st.method.p": "Cases, votes and individual votes are retrieved automatically from data.stortinget.no (open data, NLOD). We include budget cases (Prop. 1 S and amendments, revised national budget, supplementary appropriations) in the two latest sessions, and cases whose title, topic or proposal text mention aid, Ukraine/Nansen, UN and international organisations/EEA, the Follo Line or the Government Quarter (sessions from 2013–2014 for these areas). The area link is a keyword text search (pipeline/config/storting.json) and can produce both false hits and misses. Votes without recorded individual votes (e.g. unanimously adopted) have no party or representative breakdown.",
};
