/** Tekster som gjelder ekte data (overstyrer eldre demotekster i dict.ts). */
export const realNb: Record<string, string> = {
  na: "ikke tilgjengelig", "ticker.na": "Vedtatt budsjett for {year} er ikke tilgjengelig i datasettet. Telleren vises ikke.",
  "nature.capital": "Kapitalinnskudd/risikokapital", "commitment.obligatory": "Pliktige bidrag",
  "commitment.political": "Politisk vedtatt (ikke ekstern binding etter postens ordlyd)",
  "ticker.lead": "Fordeling av vedtatt statsbudsjett {year} for utgifter til utlandet, hittil i år",
  "ticker.disclaimer": "Dette er en jevn fordeling av årets vedtatte budsjett (poster i avgrensningen) over året. Det er ikke sanntidstransaksjoner, og ikke faktisk utbetalt.",
  "footer.disclaimer": "Telleren er en fordeling av budsjettvedtak, ikke faktiske transaksjoner. «Hva kunne vi gjort?» er beregninger med forutsetninger, ikke fakta.",
  "footer.never": "aldri",
  "hist.title": "Netto bistand utbetalt, siste 10 år (OECD DAC)", "hist.legend": "Utbetalt (regnskapstall fra OECD DAC), bilateral og multilateral ODA, uten flyktningutgifter i Norge. Lys søyle: foreløpig år med kun totaler. ODA-avgrensning, ikke statsbudsjettets poster.", prelim: "foreløpig",
  "hist.real": "Faste {year}-kroner",
  "home.scope2": "Vi teller vedtatte poster i statsbudsjettet (Prop. 1 S) som er overføringer til mottakere utenfor Norge, avgrenset til kapitlene og postene under. Flyktningutgifter i Norge og drift av utenrikstjenesten er ikke med. Definisjonen ligger i docs/metode.md og er forklart under Metode og kilder.",
  "map.intro": "Land er farget etter netto utbetalt bistand (ODA) for valgt år, fra OECD DAC. Klikk på et land (eller en rad) for detaljer. Multilaterale bidrag og ufordelte bidrag vises i egen liste.",
  "src.notretrieved": "ikke hentet",
  "cat.intro": "Vedtatt statsbudsjett for utlandsposter etter formål. Hver post har lenke til Stortingets vedtak. Klassifisering av gave/kapital og pliktige bidrag er manuelt kuratert etter postenes navn.",
  "cat.budgetYear": "Budsjettår", "cat.basis": "Vedtatt budsjett, løpende kroner: {total}. Hentet {date}.", "cat.nominal": "Løpende kroner.", "cat.na": "Ingen vedtatte budsjettposter er tilgjengelige.",
  "cat.lines": "Poster ({n})", "cat.item": "Kapittel.post", "cat.vote": "votering", "cat.out.h": "Poster utenfor avgrensningen",
  "cat.out.p": "Kapitler i utenriks- og forsvarsbudsjettet som ikke er regnet med (drift, utgifter i Norge m.m.). Vises for åpenhet.",
  "cat.out.show": "Vis {n} poster", "cat.out.hide": "Skjul poster",
  "calc.na.h": "Enhetspriser og skatteproveny", "calc.na.p": "Ikke tilgjengelig. Ingen kilder til enhetspriser (sykehjemsplass, lærerårsverk, vei) eller provenyanslag er koblet ennå, og vi bruker ikke tall uten kilde. Se docs/datahull.md.",
  "calc.share": "andel av BNP", "calc.share.note": "Beløpet delt på BNP for {year} (SSB, løpende priser).",
  "calc.scenario": "Beregning, ikke fakta",
  "calc.ctx.c3": "Bruttobeløp i løpende kroner for angitt år; ingen justering for prisvekst.",
  "calc.intro": "Velg en sum og se hva den tilsvarer per innbygger og som andel av BNP. Dette er beregninger med forutsetninger, ikke anbefalinger eller prognoser.",
  "method.intro": "Hvordan tallene er hentet, avgrenset og regnet om. Alt som ikke er tilgjengelig er merket.",
  "method.scope.h": "Hva teller vi?", "method.scope.p": "Utgifter til utlandet er definert som vedtatte poster i statsbudsjettets utgiftsdel som er overføringer til mottakere utenfor Norge: humanitær bistand, fred og menneskerettigheter, regional og tematisk bistand, miljø og klima, støtte til Ukraina, multilaterale organisasjoner og pliktige bidrag, EØS-finansieringsordningene og bidrag til NATO. Kapittel og post for hver kategori står i definisjonsfilen (pipeline/config/definition.json) og vises post for post under Kategorier.\nUtenfor: drift av utenrikstjenesten, kultur- og næringsfremme, flyktningutgifter i Norge og forsvarets egen drift. Definisjonen er manuelt kuratert og kontrollert mot budsjettårene 2025 og 2026.",
  "method.counter.h": "Telleren", "method.counter.p": "Telleren tar vedtatt budsjett for året (sum av postene i avgrensningen, slik Stortinget vedtok dem i desember året før) og fordeler beløpet jevnt over sekundene i året (Europe/Oslo). Den er en fordeling av budsjettvedtak, ikke sanntidstransaksjoner. Revidert nasjonalbudsjett og tilleggsbevilgninger er ikke innarbeidet.",
  "method.basis.h": "Vedtatt, utbetalt og estimat", "method.basis.p": "Vedtatt: beløp Stortinget har vedtatt for budsjettåret (statsbudsjettet). Utbetalt: bistand utbetalt ifølge OECD DAC (netto utbetalinger, ODA-avgrensning). Estimat: brukes ikke. Hver rad viser beløpstype, kilde og hentedato.",
  "method.prices.h": "Løpende og faste kroner", "method.prices.p": "Alle beløp lagres i løpende kroner. OECD-tall oppgis i USD og regnes om til kroner med OECDs implisitte årskurs (totalt netto ODA i kroner delt på i dollar for samme år), slik at summen stemmer med OECDs norske totaler. Faste kroner regnes om med SSBs konsumprisindeks (årsgjennomsnitt); nyeste hele år er basisår. Faste kroner mangler for år uten KPI.",
  "method.classify.h": "Kategorisering", "method.classify.p": "Budsjettpostene fordeles på kategorier etter kapittel og post (definition.json). En regel som forventer et bestemt postnavn feiler i pipelinen hvis navnet endres, og bistandskapitler uten regel gir feil. Kategoriene i kartet (bilateral, multilateral, flyktningutgifter) følger OECD og er ikke det samme som budsjettkategoriene.",
  "method.contrib.h": "Gaver, kapital og forpliktelser", "method.contrib.p": "Vi skiller etter postens navn: tilskudd (gave), risikokapital/kapitalinnskudd, medlemskap (NATO) og pliktige bidrag. EØS-finansieringsordningene er klassifisert som avtalefestet og NATO som traktatfestet medlemskap. Klassifiseringen er manuell og ikke hentet fra en kilde. Lån finnes ikke som egne poster i avgrensningen.",
  "method.excluded.h": "Hva er ikke med", "method.excluded.p": "Flyktningutgifter i Norge (vises i OECD-tallene, men ikke i telleren), drift av utenrikstjenesten, Oljefondets investeringer, kapittel 118 (utenrikspolitiske tilskudd) og kap. 1750 post 21 (for å unngå dobbelttelling; posten kan nyttes under post 79).",
  "method.whatif.h": "Beregninger («Hva kunne vi gjort?»)", "method.whatif.p": "Beregningene viser beløp per innbygger og som andel av BNP, med tall fra SSB. Enhetspriser og skatteproveny er ikke tilgjengelige og vises ikke. Beregninger er ikke fakta.",
  "method.gaps.h": "Kjente hull", "method.gaps.p": "Se listen «Ikke tilgjengelig» under. Kort: faktisk utbetalt per budsjettpost (statsregnskapet), prosjekter og mottakere fra Norad, revidert budsjett, antall skattytere og enhetspriser er ikke koblet.\nKartet bruker en forenklet verdensgeometri uten små øystater.",
  "method.sources.h": "Datakilder", "method.sources.p": "Status per kilde ved siste kjøring ({date}).",
  "col.license": "Lisens/vilkår", "col.frequency": "Oppdatering", "col.kind": "Hentes",
  "method.auto.h": "Automatisk hentet og manuelt kuratert", "method.auto.auto": "Automatisk (kode henter fra kilden ved hver kjøring)", "method.manual": "Manuelt kuratert eller ikke tilgjengelig",
  "method.manual.list": "Definisjonen av hva som teller som utgift til utlandet (definition.json), klassifisering av gave/kapital/pliktige bidrag, og godkjente prosjekttall (data/review/approved). Kontrollkilder som ikke er tilgjengelige fra pipelinen står som «krever manuell import».",
  "method.unavailable.h": "Ikke tilgjengelig", "method.def.h": "Definisjon",
  "status.manual_needed": "Ikke hentet automatisk",
};
export const realEn: Record<string, string> = {
  na: "not available", "ticker.na": "The adopted budget for {year} is not available in the dataset. The counter is not shown.",
  "nature.capital": "Capital injection/risk capital", "commitment.obligatory": "Assessed contributions",
  "commitment.political": "Politically decided (no external binding by the wording of the item)",
  "ticker.lead": "Distribution of the adopted {year} state budget for spending abroad, so far this year",
  "ticker.disclaimer": "This is an even distribution of the year's adopted budget (items within the definition) across the year. It is not real-time transactions and not actual disbursements.",
  "footer.disclaimer": "The counter is a distribution of budget decisions, not actual transactions. “What could we do?” shows calculations with assumptions, not fact.",
  "footer.never": "never",
  "hist.title": "Net aid disbursed, last 10 years (OECD DAC)", "hist.legend": "Disbursed (accounts from the OECD DAC), bilateral and multilateral ODA, excluding in-donor refugee costs. Light bar: preliminary year with totals only. ODA scope, not the budget items.", prelim: "preliminary",
  "hist.real": "Constant {year} NOK",
  "home.scope2": "We count adopted items in the state budget (Prop. 1 S) that are transfers to recipients outside Norway, limited to the chapters and items below. Refugee costs in Norway and the running of the foreign service are excluded. The definition is in docs/metode.md and explained under Method and sources.",
  "map.intro": "Countries are coloured by net aid (ODA) disbursed in the selected year, from the OECD DAC. Click a country (or a row) for details. Multilateral and unallocated contributions are listed separately.",
  "src.notretrieved": "not retrieved",
  "cat.intro": "Adopted state budget for foreign items by purpose. Every item links to the Storting's decision. Classification of grant/capital and assessed contributions is manually curated from the item names.",
  "cat.budgetYear": "Budget year", "cat.basis": "Adopted budget, current NOK: {total}. Retrieved {date}.", "cat.nominal": "Current NOK.", "cat.na": "No adopted budget items are available.",
  "cat.lines": "Items ({n})", "cat.item": "Chapter.item", "cat.vote": "vote", "cat.out.h": "Items outside the definition",
  "cat.out.p": "Chapters in the foreign and defence budgets that are not counted (running costs, spending in Norway, etc.). Shown for transparency.",
  "cat.out.show": "Show {n} items", "cat.out.hide": "Hide items",
  "calc.na.h": "Unit costs and tax revenue", "calc.na.p": "Not available. No sources for unit costs (nursing-home place, teacher FTE, road) or revenue estimates are connected yet, and we do not use figures without a source. See docs/datahull.md.",
  "calc.share": "share of GDP", "calc.share.note": "The amount divided by GDP for {year} (Statistics Norway, current prices).",
  "calc.scenario": "Calculation, not fact",
  "calc.ctx.c3": "Gross amounts in current kroner for the given year; no adjustment for price growth.",
  "calc.intro": "Pick an amount and see what it equals per resident and as a share of GDP. These are calculations with assumptions, not recommendations or forecasts.",
  "method.intro": "How the figures are retrieved, delimited and converted. Anything not available is flagged.",
  "method.scope.h": "What do we count?", "method.scope.p": "Spending abroad is defined as adopted items in the expenditure part of the state budget that are transfers to recipients outside Norway: humanitarian aid, peace and human rights, regional and thematic aid, environment and climate, support to Ukraine, multilateral organisations and assessed contributions, the EEA financing mechanisms and contributions to NATO. Chapter and item for each category are in the definition file (pipeline/config/definition.json) and shown item by item under Categories.\nExcluded: running costs of the foreign service, culture and business promotion, refugee costs in Norway and the defence forces' own operations. The definition is manually curated and checked against budget years 2025 and 2026.",
  "method.counter.h": "The counter", "method.counter.p": "The counter takes the adopted budget for the year (sum of the items in the definition, as adopted by the Storting in December the year before) and spreads it evenly over the seconds of the year (Europe/Oslo). It is a distribution of budget decisions, not real-time transactions. The revised national budget and supplementary appropriations are not incorporated.",
  "method.basis.h": "Adopted, disbursed and estimate", "method.basis.p": "Adopted: amounts the Storting adopted for the budget year (state budget). Disbursed: aid disbursed according to the OECD DAC (net disbursements, ODA scope). Estimate: not used. Every row shows its amount type, source and retrieval date.",
  "method.prices.h": "Current and constant kroner", "method.prices.p": "All amounts are stored in current kroner. OECD figures are in USD and converted to kroner with the OECD's implied annual rate (total net ODA in kroner divided by that in dollars for the same year), so that sums match the OECD's Norwegian totals. Constant kroner use Statistics Norway's CPI (annual average); the latest full year is the base year. Constant kroner are missing for years without a CPI.",
  "method.classify.h": "Categorisation", "method.classify.p": "Budget items are assigned to categories by chapter and item (definition.json). A rule that expects a certain item name fails in the pipeline if the name changes, and aid chapters without a rule cause an error. The map categories (bilateral, multilateral, refugee costs) follow the OECD and differ from the budget categories.",
  "method.contrib.h": "Grants, capital and commitments", "method.contrib.p": "We distinguish by item name: grants, risk capital/capital injections, membership (NATO) and assessed contributions. The EEA financing mechanisms are classified as agreement-based and NATO as treaty-based membership. The classification is manual and not retrieved from a source. Loans do not appear as separate items in the definition.",
  "method.excluded.h": "What is not included", "method.excluded.p": "Refugee costs in Norway (shown in the OECD figures but not in the counter), running costs of the foreign service, the Government Pension Fund's investments, chapter 118 (foreign policy grants) and chapter 1750 item 21 (to avoid double counting; the item may be used under item 79).",
  "method.whatif.h": "Calculations (“What could we do?”)", "method.whatif.p": "The calculations show amounts per resident and as a share of GDP, with figures from Statistics Norway. Unit costs and tax revenue are not available and not shown. Calculations are not fact.",
  "method.gaps.h": "Known gaps", "method.gaps.p": "See the “Not available” list below. In short: actual disbursements per budget item (state accounts), projects and recipients from Norad, the revised budget, number of taxpayers and unit costs are not connected.\nThe map uses a simplified world geometry without small island states.",
  "method.sources.h": "Data sources", "method.sources.p": "Status per source at the last run ({date}).",
  "col.license": "Licence/terms", "col.frequency": "Update frequency", "col.kind": "Retrieval",
  "method.auto.h": "Automatically retrieved and manually curated", "method.auto.auto": "Automatic (code retrieves from the source on every run)", "method.manual": "Manually curated or not available",
  "method.manual.list": "The definition of what counts as spending abroad (definition.json), the grant/capital/assessed classification, and approved project figures (data/review/approved). Control sources that are unreachable from the pipeline are shown as “needs manual import”.",
  "method.unavailable.h": "Not available", "method.def.h": "Definition",
  "status.manual_needed": "Not retrieved automatically",
};
